### PR TITLE
Implement PackageRetrieve

### PR DESCRIPTION
**Pull request by leng20000**
Still unsure about how to test the API for PackageRetrieve

### CODE REVIEW

**Comment by starliteSeeker** [comment]
Well you have to fix the error first before testing the code.
First error is telling you to use await, second is telling you to derive the necessary traits.

**Comment by leng20000** [comment]
The error is on the base64 conversion function, I'm not sure if this is how you call the function: 

https://github.com/lee3445/module-registry/blob/3948b93c51292374099cda9057865d14aea4c7bb/src/api.rs#L48

**Comment by leng20000** [comment]
Within the module_registry directory I created a 'packages' folder with 'postcss.txt' inside. I then tested with zip_to_base64 function, but it keeps giving me Err. How did you test this function?

**Comment by starliteSeeker** [comment]
Hmm.. Make sure you set the path field when initializing the Module struct in `Module::new()`, maybe something like `./packages/<id>`. Also make sure you're running the program in the right location.

**Comment by starliteSeeker** [comment]
So there are 2 fields in Module: `ver` and `version`. I failed to pick a better name when adding them, but what you want is `ver`. `version` is one of the metrics.

It's technically not possible to fail on the unwrap() in `api.rs` line 45 if we write our code perfectly, but I would prefer if you do some error handling, maybe returning 500 for server error. For the unwrap in `api.rs` line 36, I believe you can use `unwrap_or()`.

In the PackageData type, only one of Content and URL should be set. Enum should be useful here.

**Comment by leng20000** [comment]
I changed the code to use `ver` within the latest commit. 

Do we need to handle the error for the conversion though? I thought if the upload package works properly and is in the right folder then it should run properly? 

Last thing, I'm not sure why we use Enum in this case because I thought we need to return both the Content and the URL?

**Comment by starliteSeeker** [comment]
You are right on handling the error for conversion if we also consider the behavior of other parts of the program, but looking at the function by itself, there is still a chance it can fail. (That said, I think if a thread panics in rocket because unwrapping fails, rocket returns 500 for us, so it's fine to forget what I said and not add error handling)

For PackageData, the description in the yaml file is a bit awkward, but looking at the examples, it seems like only one of Content and URL should be present. Check out the examples in GET /package/<id>.

**Comment by leng20000** [comment]
I still don't quite get the PackageData part, do you mean either the Content or URL should be set? So it would either have the field `Content and JSProgram` or `URL and JSProgram`? 

image


Also, I couldn't find the GET /package/ example that you're referring. Is it in the yaml file and which lines is it in?

**Comment by starliteSeeker** [comment]
Oh no, it appears they've updated the specification again. So in 151-160 and 256-265, Content and JSProgram are set. In 134-144, all 3 are set. Based on the description of the PackageData structure in 561-565, it is a "union" type, so only one of them should be set (either `Content and JSProgram` or `URL and JSProgram`).

I have no clue what they want now, so I guess just wrap both Content and JSProgram in Options and make sure to handle the case where both fields don't exist.

**Comment by leng20000** [comment]
I think we have different specification files because the line number that you provided doesn't match. Regardless of that I wrapped the Content field with Options. It should be good now, do you think I should add anything else?

**Comment by starliteSeeker** [comment]
I removed PathBuf from `database.rs` since you're not using it anymore. Looks good otherwise.

**Review by starliteSeeker — APPROVED** [review]

**Pull request merged**
